/*
 * HCTR++ validation: POLYVAL256 unit vectors, mode KATs generated by the
 * Python executable specification, in-place operation, and round-trips.
 * MIT license.
 */
#include <stdio.h>
#include <string.h>
#include "src/hctrpp.c" /* unity build: gives the tests access to internals */
#include "testvectors/hctrpp_kat.h"

static int failures;

static void check(int ok, const char *what, size_t a, size_t b)
{
    if (!ok) {
        printf("FAIL: %s (case %zu/%zu)\n", what, a, b);
        failures++;
    }
}

/* Raw POLYVAL256 (no length/tweak encoding) for the unit vectors. */
static void polyval256_raw(const uint8_t key[32], const uint8_t *msg,
                           size_t len, uint8_t out[32])
{
    gf256 hp, s;
    hp.lo = _mm_loadu_si128((const __m128i *)key);
    hp.hi = _mm_loadu_si128((const __m128i *)(key + 16));
    s.lo = _mm_setzero_si128();
    s.hi = _mm_setzero_si128();
    for (size_t i = 0; i < len; i += 32)
        s = hash_absorb(s, hp, msg + i);
    _mm_storeu_si128((__m128i *)out, s.lo);
    _mm_storeu_si128((__m128i *)(out + 16), s.hi);
}

int main(void)
{
    uint8_t buf[1024], buf2[1024], dig[32];

    /* POLYVAL256 unit vectors */
    polyval256_raw(pv_key, pv0_msg, sizeof(pv0_msg), dig);
    check(memcmp(dig, pv0_dig, 32) == 0, "polyval256 vector", 0, 2);
    polyval256_raw(pv_key, pv1_msg, sizeof(pv1_msg), dig);
    check(memcmp(dig, pv1_dig, 32) == 0, "polyval256 vector", 1, 2);

    /* Mode KATs from the Python specification */
    size_t nkat = sizeof(hctrpp_kats) / sizeof(hctrpp_kats[0]);
    for (size_t i = 0; i < nkat; i++) {
        const hctrpp_kat_t *k = &hctrpp_kats[i];
        hctrpp_ctx ctx;
        hctrpp_init(&ctx, k->key);

        hctrpp_encrypt(&ctx, k->pt, k->msg_len, k->tweak, k->tweak_len, buf);
        check(memcmp(buf, k->ct, k->msg_len) == 0, "KAT encrypt", i, nkat);

        hctrpp_decrypt(&ctx, k->ct, k->msg_len, k->tweak, k->tweak_len, buf);
        check(memcmp(buf, k->pt, k->msg_len) == 0, "KAT decrypt", i, nkat);

        /* in-place */
        memcpy(buf, k->pt, k->msg_len);
        hctrpp_encrypt(&ctx, buf, k->msg_len, k->tweak, k->tweak_len, buf);
        check(memcmp(buf, k->ct, k->msg_len) == 0, "KAT in-place", i, nkat);
    }

    /* Round-trips over odd lengths and tweak lengths */
    uint32_t lcg = 0x1234567;
    uint8_t key[16], twk[64], msg[1024];
    for (size_t i = 0; i < sizeof(msg); i++) {
        lcg = lcg * 1664525u + 1013904223u;
        msg[i] = (uint8_t)(lcg >> 24);
        if (i < 16) key[i] = (uint8_t)(lcg >> 16);
        if (i < 64) twk[i] = (uint8_t)(lcg >> 8);
    }
    hctrpp_ctx ctx;
    hctrpp_init(&ctx, key);
    size_t rt = 0;
    for (size_t len = 16; len <= 1024; len += 7, rt++) {
        size_t tlen = (len * 13) % 64;
        int rc = hctrpp_encrypt(&ctx, msg, len, twk, tlen, buf);
        rc |= hctrpp_decrypt(&ctx, buf, len, twk, tlen, buf2);
        check(rc == 0 && memcmp(buf2, msg, len) == 0, "round-trip", len, 0);
    }

    /* Invalid inputs must be rejected */
    check(hctrpp_encrypt(&ctx, msg, 15, twk, 16, buf) < 0, "reject len<16", 0, 0);
    check(hctrpp_encrypt(&ctx, NULL, 32, twk, 16, buf) < 0, "reject NULL", 0, 0);

    if (failures) {
        printf("VALIDATION FAILED: %d failure(s)\n", failures);
        return 1;
    }
    printf("HCTR++ validation OK: 2 polyval256 vectors, %zu mode KATs "
           "(enc/dec/in-place), %zu round-trips\n", nkat, rt);
    return 0;
}
